# Generated by Django 4.2.1 on 2023-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeedetail_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
